version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - streamlit build home.py

artifacts:
  files:
    - home.py
    - requirements.txt
  discard-paths: yes
